arrowParens: avoid
bracketSpacing: true
endOfLine: auto
printWidth: 120
singleQuote: true
tabWidth: 2
trailingComma: all
semi: false

overrides:
  - files: '*.sol'
    options:
      tabWidth: 4
      singleQuote: false
      semi: true
